package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityTable generated by hbm2java
 */
@Entity
@Table(name = "activity_table", catalog = "itradb")
public class ActivityTable implements java.io.Serializable {

	private Integer id;
	private DestinationTable destinationTable;
	private String activityName;
	private String activityDescription;
	private Integer activityMultiImageId;
	private String activityVideo;
	private Set activityImages = new HashSet(0);

	public ActivityTable() {
	}

	public ActivityTable(DestinationTable destinationTable,
			String activityName, String activityDescription,
			Integer activityMultiImageId, String activityVideo,
			Set activityImages) {
		this.destinationTable = destinationTable;
		this.activityName = activityName;
		this.activityDescription = activityDescription;
		this.activityMultiImageId = activityMultiImageId;
		this.activityVideo = activityVideo;
		this.activityImages = activityImages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_destination")
	public DestinationTable getDestinationTable() {
		return this.destinationTable;
	}

	public void setDestinationTable(DestinationTable destinationTable) {
		this.destinationTable = destinationTable;
	}

	@Column(name = "activity_name", length = 40)
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Column(name = "activity_description", length = 300)
	public String getActivityDescription() {
		return this.activityDescription;
	}

	public void setActivityDescription(String activityDescription) {
		this.activityDescription = activityDescription;
	}

	@Column(name = "activity_multi_image_id")
	public Integer getActivityMultiImageId() {
		return this.activityMultiImageId;
	}

	public void setActivityMultiImageId(Integer activityMultiImageId) {
		this.activityMultiImageId = activityMultiImageId;
	}

	@Column(name = "activity_video", length = 200)
	public String getActivityVideo() {
		return this.activityVideo;
	}

	public void setActivityVideo(String activityVideo) {
		this.activityVideo = activityVideo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityTable")
	public Set getActivityImages() {
		return this.activityImages;
	}

	public void setActivityImages(Set activityImages) {
		this.activityImages = activityImages;
	}

}
