package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityImage generated by hbm2java
 */
@Entity
@Table(name = "activity_image", catalog = "itradb")
public class ActivityImage implements java.io.Serializable {

	private Integer id;
	private ActivityTable activityTable;
	private byte[] activityImage;

	public ActivityImage() {
	}

	public ActivityImage(ActivityTable activityTable, byte[] activityImage) {
		this.activityTable = activityTable;
		this.activityImage = activityImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id")
	public ActivityTable getActivityTable() {
		return this.activityTable;
	}

	public void setActivityTable(ActivityTable activityTable) {
		this.activityTable = activityTable;
	}

	@Column(name = "activity_image")
	public byte[] getActivityImage() {
		return this.activityImage;
	}

	public void setActivityImage(byte[] activityImage) {
		this.activityImage = activityImage;
	}

}
