package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CountryTable generated by hbm2java
 */
@Entity
@Table(name = "country_table", catalog = "itradb")
public class CountryTable implements java.io.Serializable {

	private Integer id;
	private String country;
	private String description;
	private Set destinationTables = new HashSet(0);
	private Set supplierTables = new HashSet(0);
	private Set packageTables = new HashSet(0);
	private Set hotelTables = new HashSet(0);

	public CountryTable() {
	}

	public CountryTable(String country, String description,
			Set destinationTables, Set supplierTables, Set packageTables,
			Set hotelTables) {
		this.country = country;
		this.description = description;
		this.destinationTables = destinationTables;
		this.supplierTables = supplierTables;
		this.packageTables = packageTables;
		this.hotelTables = hotelTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "country", length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTable")
	public Set getDestinationTables() {
		return this.destinationTables;
	}

	public void setDestinationTables(Set destinationTables) {
		this.destinationTables = destinationTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTable")
	public Set getSupplierTables() {
		return this.supplierTables;
	}

	public void setSupplierTables(Set supplierTables) {
		this.supplierTables = supplierTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryTable")
	public Set getHotelTables() {
		return this.hotelTables;
	}

	public void setHotelTables(Set hotelTables) {
		this.hotelTables = hotelTables;
	}

}
