package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CurrencyLookupTable generated by hbm2java
 */
@Entity
@Table(name = "currency_lookup_table", catalog = "itradb")
public class CurrencyLookupTable implements java.io.Serializable {

	private Integer id;
	private String currencyName;
	private String currencySymbol;
	private Set packageTables = new HashSet(0);

	public CurrencyLookupTable() {
	}

	public CurrencyLookupTable(String currencyName, String currencySymbol,
			Set packageTables) {
		this.currencyName = currencyName;
		this.currencySymbol = currencySymbol;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "currency_name", length = 40)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@Column(name = "currency_symbol", length = 5)
	public String getCurrencySymbol() {
		return this.currencySymbol;
	}

	public void setCurrencySymbol(String currencySymbol) {
		this.currencySymbol = currencySymbol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currencyLookupTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
