package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DestinationImage generated by hbm2java
 */
@Entity
@Table(name = "destination_image", catalog = "itradb")
public class DestinationImage implements java.io.Serializable {

	private Integer id;
	private DestinationTable destinationTable;
	private byte[] destinationImage;

	public DestinationImage() {
	}

	public DestinationImage(DestinationTable destinationTable,
			byte[] destinationImage) {
		this.destinationTable = destinationTable;
		this.destinationImage = destinationImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destination_id")
	public DestinationTable getDestinationTable() {
		return this.destinationTable;
	}

	public void setDestinationTable(DestinationTable destinationTable) {
		this.destinationTable = destinationTable;
	}

	@Column(name = "destination_image")
	public byte[] getDestinationImage() {
		return this.destinationImage;
	}

	public void setDestinationImage(byte[] destinationImage) {
		this.destinationImage = destinationImage;
	}

}
