package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DestinationTable generated by hbm2java
 */
@Entity
@Table(name = "destination_table", catalog = "itradb")
public class DestinationTable implements java.io.Serializable {

	private Integer id;
	private CountryTable countryTable;
	private String destinationName;
	private String destinationInfo;
	private Integer destinationImageId;
	private String destinationVideo;
	private Set activityTables = new HashSet(0);
	private Set supplierTables = new HashSet(0);
	private Set packageTables = new HashSet(0);
	private Set destinationImages = new HashSet(0);
	private Set hotelTables = new HashSet(0);

	public DestinationTable() {
	}

	public DestinationTable(CountryTable countryTable, String destinationName,
			String destinationInfo, Integer destinationImageId,
			String destinationVideo, Set activityTables, Set supplierTables,
			Set packageTables, Set destinationImages, Set hotelTables) {
		this.countryTable = countryTable;
		this.destinationName = destinationName;
		this.destinationInfo = destinationInfo;
		this.destinationImageId = destinationImageId;
		this.destinationVideo = destinationVideo;
		this.activityTables = activityTables;
		this.supplierTables = supplierTables;
		this.packageTables = packageTables;
		this.destinationImages = destinationImages;
		this.hotelTables = hotelTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country")
	public CountryTable getCountryTable() {
		return this.countryTable;
	}

	public void setCountryTable(CountryTable countryTable) {
		this.countryTable = countryTable;
	}

	@Column(name = "destination_name", length = 40)
	public String getDestinationName() {
		return this.destinationName;
	}

	public void setDestinationName(String destinationName) {
		this.destinationName = destinationName;
	}

	@Column(name = "destination_info", length = 300)
	public String getDestinationInfo() {
		return this.destinationInfo;
	}

	public void setDestinationInfo(String destinationInfo) {
		this.destinationInfo = destinationInfo;
	}

	@Column(name = "destination_image_id")
	public Integer getDestinationImageId() {
		return this.destinationImageId;
	}

	public void setDestinationImageId(Integer destinationImageId) {
		this.destinationImageId = destinationImageId;
	}

	@Column(name = "destination_video", length = 2000)
	public String getDestinationVideo() {
		return this.destinationVideo;
	}

	public void setDestinationVideo(String destinationVideo) {
		this.destinationVideo = destinationVideo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinationTable")
	public Set getActivityTables() {
		return this.activityTables;
	}

	public void setActivityTables(Set activityTables) {
		this.activityTables = activityTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinationTable")
	public Set getSupplierTables() {
		return this.supplierTables;
	}

	public void setSupplierTables(Set supplierTables) {
		this.supplierTables = supplierTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinationTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinationTable")
	public Set getDestinationImages() {
		return this.destinationImages;
	}

	public void setDestinationImages(Set destinationImages) {
		this.destinationImages = destinationImages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinationTable")
	public Set getHotelTables() {
		return this.hotelTables;
	}

	public void setHotelTables(Set hotelTables) {
		this.hotelTables = hotelTables;
	}

}
