package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HotelTable generated by hbm2java
 */
@Entity
@Table(name = "hotel_table", catalog = "itradb")
public class HotelTable implements java.io.Serializable {

	private Integer id;
	private DestinationTable destinationTable;
	private CountryTable countryTable;
	private String hotelName;
	private Integer hotelCategory;
	private String hotelDescription;
	private Integer hotelImageId;
	private String hotelVideo;
	private Integer hotelAmenitiesMapId;
	private String hotelContactPerson;
	private Integer hotelContactPersonNumber;
	private String hotelContactPersonEmail;
	private String hotelAddress;
	private Integer hotelContactNumber;
	private String hotelEmail;
	private Set packageTables = new HashSet(0);
	private Set hotelImages = new HashSet(0);
	private Set hotelAmenitiesLookupTables = new HashSet(0);

	public HotelTable() {
	}

	public HotelTable(DestinationTable destinationTable,
			CountryTable countryTable, String hotelName, Integer hotelCategory,
			String hotelDescription, Integer hotelImageId, String hotelVideo,
			Integer hotelAmenitiesMapId, String hotelContactPerson,
			Integer hotelContactPersonNumber, String hotelContactPersonEmail,
			String hotelAddress, Integer hotelContactNumber, String hotelEmail,
			Set packageTables, Set hotelImages, Set hotelAmenitiesLookupTables) {
		this.destinationTable = destinationTable;
		this.countryTable = countryTable;
		this.hotelName = hotelName;
		this.hotelCategory = hotelCategory;
		this.hotelDescription = hotelDescription;
		this.hotelImageId = hotelImageId;
		this.hotelVideo = hotelVideo;
		this.hotelAmenitiesMapId = hotelAmenitiesMapId;
		this.hotelContactPerson = hotelContactPerson;
		this.hotelContactPersonNumber = hotelContactPersonNumber;
		this.hotelContactPersonEmail = hotelContactPersonEmail;
		this.hotelAddress = hotelAddress;
		this.hotelContactNumber = hotelContactNumber;
		this.hotelEmail = hotelEmail;
		this.packageTables = packageTables;
		this.hotelImages = hotelImages;
		this.hotelAmenitiesLookupTables = hotelAmenitiesLookupTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_city")
	public DestinationTable getDestinationTable() {
		return this.destinationTable;
	}

	public void setDestinationTable(DestinationTable destinationTable) {
		this.destinationTable = destinationTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_country")
	public CountryTable getCountryTable() {
		return this.countryTable;
	}

	public void setCountryTable(CountryTable countryTable) {
		this.countryTable = countryTable;
	}

	@Column(name = "hotel_name", length = 100)
	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	@Column(name = "hotel_category")
	public Integer getHotelCategory() {
		return this.hotelCategory;
	}

	public void setHotelCategory(Integer hotelCategory) {
		this.hotelCategory = hotelCategory;
	}

	@Column(name = "hotel_description", length = 300)
	public String getHotelDescription() {
		return this.hotelDescription;
	}

	public void setHotelDescription(String hotelDescription) {
		this.hotelDescription = hotelDescription;
	}

	@Column(name = "hotel_image_id")
	public Integer getHotelImageId() {
		return this.hotelImageId;
	}

	public void setHotelImageId(Integer hotelImageId) {
		this.hotelImageId = hotelImageId;
	}

	@Column(name = "hotel_video", length = 200)
	public String getHotelVideo() {
		return this.hotelVideo;
	}

	public void setHotelVideo(String hotelVideo) {
		this.hotelVideo = hotelVideo;
	}

	@Column(name = "hotel_amenities_map_id")
	public Integer getHotelAmenitiesMapId() {
		return this.hotelAmenitiesMapId;
	}

	public void setHotelAmenitiesMapId(Integer hotelAmenitiesMapId) {
		this.hotelAmenitiesMapId = hotelAmenitiesMapId;
	}

	@Column(name = "hotel_contact_person", length = 200)
	public String getHotelContactPerson() {
		return this.hotelContactPerson;
	}

	public void setHotelContactPerson(String hotelContactPerson) {
		this.hotelContactPerson = hotelContactPerson;
	}

	@Column(name = "hotel_contact_person_number")
	public Integer getHotelContactPersonNumber() {
		return this.hotelContactPersonNumber;
	}

	public void setHotelContactPersonNumber(Integer hotelContactPersonNumber) {
		this.hotelContactPersonNumber = hotelContactPersonNumber;
	}

	@Column(name = "hotel_contact_person_email", length = 40)
	public String getHotelContactPersonEmail() {
		return this.hotelContactPersonEmail;
	}

	public void setHotelContactPersonEmail(String hotelContactPersonEmail) {
		this.hotelContactPersonEmail = hotelContactPersonEmail;
	}

	@Column(name = "hotel_address", length = 300)
	public String getHotelAddress() {
		return this.hotelAddress;
	}

	public void setHotelAddress(String hotelAddress) {
		this.hotelAddress = hotelAddress;
	}

	@Column(name = "hotel_contact_number")
	public Integer getHotelContactNumber() {
		return this.hotelContactNumber;
	}

	public void setHotelContactNumber(Integer hotelContactNumber) {
		this.hotelContactNumber = hotelContactNumber;
	}

	@Column(name = "hotel_email", length = 40)
	public String getHotelEmail() {
		return this.hotelEmail;
	}

	public void setHotelEmail(String hotelEmail) {
		this.hotelEmail = hotelEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotelTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotelTable")
	public Set getHotelImages() {
		return this.hotelImages;
	}

	public void setHotelImages(Set hotelImages) {
		this.hotelImages = hotelImages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hotelTable")
	public Set getHotelAmenitiesLookupTables() {
		return this.hotelAmenitiesLookupTables;
	}

	public void setHotelAmenitiesLookupTables(Set hotelAmenitiesLookupTables) {
		this.hotelAmenitiesLookupTables = hotelAmenitiesLookupTables;
	}

}
