package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HotelAmenitiesLookupTable generated by hbm2java
 */
@Entity
@Table(name = "hotel_amenities_lookup_table", catalog = "itradb")
public class HotelAmenitiesLookupTable implements java.io.Serializable {

	private Integer id;
	private HotelTable hotelTable;
	private String category;
	private String amenityName;

	public HotelAmenitiesLookupTable() {
	}

	public HotelAmenitiesLookupTable(HotelTable hotelTable, String category,
			String amenityName) {
		this.hotelTable = hotelTable;
		this.category = category;
		this.amenityName = amenityName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id")
	public HotelTable getHotelTable() {
		return this.hotelTable;
	}

	public void setHotelTable(HotelTable hotelTable) {
		this.hotelTable = hotelTable;
	}

	@Column(name = "category", length = 40)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "amenity_name", length = 40)
	public String getAmenityName() {
		return this.amenityName;
	}

	public void setAmenityName(String amenityName) {
		this.amenityName = amenityName;
	}

}
