package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HotelImage generated by hbm2java
 */
@Entity
@Table(name = "hotel_image", catalog = "itradb")
public class HotelImage implements java.io.Serializable {

	private Integer id;
	private HotelTable hotelTable;
	private byte[] hotelImage;

	public HotelImage() {
	}

	public HotelImage(HotelTable hotelTable, byte[] hotelImage) {
		this.hotelTable = hotelTable;
		this.hotelImage = hotelImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hotel_id")
	public HotelTable getHotelTable() {
		return this.hotelTable;
	}

	public void setHotelTable(HotelTable hotelTable) {
		this.hotelTable = hotelTable;
	}

	@Column(name = "hotel_image")
	public byte[] getHotelImage() {
		return this.hotelImage;
	}

	public void setHotelImage(byte[] hotelImage) {
		this.hotelImage = hotelImage;
	}

}
