package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItineraryTypeLookupTable generated by hbm2java
 */
@Entity
@Table(name = "itinerary_type_lookup_table", catalog = "itradb")
public class ItineraryTypeLookupTable implements java.io.Serializable {

	private Integer id;
	private String itineraryType;
	private Set packageTables = new HashSet(0);

	public ItineraryTypeLookupTable() {
	}

	public ItineraryTypeLookupTable(String itineraryType, Set packageTables) {
		this.itineraryType = itineraryType;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "itinerary_type", length = 40)
	public String getItineraryType() {
		return this.itineraryType;
	}

	public void setItineraryType(String itineraryType) {
		this.itineraryType = itineraryType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itineraryTypeLookupTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
