package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MealPlanLookupTable generated by hbm2java
 */
@Entity
@Table(name = "meal_plan_lookup_table", catalog = "itradb")
public class MealPlanLookupTable implements java.io.Serializable {

	private Integer id;
	private String mealPlan;
	private Set packageTables = new HashSet(0);

	public MealPlanLookupTable() {
	}

	public MealPlanLookupTable(String mealPlan, Set packageTables) {
		this.mealPlan = mealPlan;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "meal_plan", length = 10)
	public String getMealPlan() {
		return this.mealPlan;
	}

	public void setMealPlan(String mealPlan) {
		this.mealPlan = mealPlan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mealPlanLookupTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
