package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PackageBudgetLookupTable generated by hbm2java
 */
@Entity
@Table(name = "package_budget_lookup_table", catalog = "itradb")
public class PackageBudgetLookupTable implements java.io.Serializable {

	private Integer id;
	private String packageBudget;
	private Set packageTables = new HashSet(0);

	public PackageBudgetLookupTable() {
	}

	public PackageBudgetLookupTable(String packageBudget, Set packageTables) {
		this.packageBudget = packageBudget;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "package_budget", length = 20)
	public String getPackageBudget() {
		return this.packageBudget;
	}

	public void setPackageBudget(String packageBudget) {
		this.packageBudget = packageBudget;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packageBudgetLookupTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
