package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PackageTypeLookupTable generated by hbm2java
 */
@Entity
@Table(name = "package_type_lookup_table", catalog = "itradb")
public class PackageTypeLookupTable implements java.io.Serializable {

	private Integer id;
	private String packageType;
	private Set packageTables = new HashSet(0);

	public PackageTypeLookupTable() {
	}

	public PackageTypeLookupTable(String packageType, Set packageTables) {
		this.packageType = packageType;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "package_type", length = 20)
	public String getPackageType() {
		return this.packageType;
	}

	public void setPackageType(String packageType) {
		this.packageType = packageType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packageTypeLookupTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
