package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackageTable generated by hbm2java
 */
@Entity
@Table(name = "package_table", catalog = "itradb")
public class PackageTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private ThemeTable themeTable;
	private SupplierTable supplierTable;
	private ItineraryTable itineraryTable;
	private ItineraryTypeLookupTable itineraryTypeLookupTable;
	private DestinationTable destinationTable;
	private PackageBudgetLookupTable packageBudgetLookupTable;
	private CurrencyLookupTable currencyLookupTable;
	private CountryTable countryTable;
	private PackageTypeLookupTable packageTypeLookupTable;
	private HotelTable hotelTable;
	private PackageCategoryLookupTable packageCategoryLookupTable;
	private MealPlanLookupTable mealPlanLookupTable;
	private String packageId;
	private String packageName;
	private int numberOfNights;
	private int numberOfDays;
	private String packageDescription;
	private String bestSeason;
	private Date validFrom;
	private Date validTo;
	private Date bookingFrom;
	private Date bookingTo;
	private String packageHighlights;
	private String termsAndConditions;
	private String packageInclusions;
	private String packageExclusions;
	private int servicesId;
	private String cancellationPolicy;
	private String packageAmenities;
	private Integer packageStatus;
	private Integer originPoints;
	private Set priceTables = new HashSet(0);
	private Set servicesLookupTables = new HashSet(0);

	public PackageTable() {
	}

	public PackageTable(DestinationTable destinationTable,
			CountryTable countryTable,
			PackageTypeLookupTable packageTypeLookupTable,
			PackageCategoryLookupTable packageCategoryLookupTable,
			String packageId, String packageName, int numberOfNights,
			int numberOfDays, String packageDescription, Date validFrom,
			Date validTo, Date bookingFrom, Date bookingTo,
			String packageHighlights, String termsAndConditions,
			String packageInclusions, String packageExclusions, int servicesId,
			String cancellationPolicy, String packageAmenities) {
		this.destinationTable = destinationTable;
		this.countryTable = countryTable;
		this.packageTypeLookupTable = packageTypeLookupTable;
		this.packageCategoryLookupTable = packageCategoryLookupTable;
		this.packageId = packageId;
		this.packageName = packageName;
		this.numberOfNights = numberOfNights;
		this.numberOfDays = numberOfDays;
		this.packageDescription = packageDescription;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.bookingFrom = bookingFrom;
		this.bookingTo = bookingTo;
		this.packageHighlights = packageHighlights;
		this.termsAndConditions = termsAndConditions;
		this.packageInclusions = packageInclusions;
		this.packageExclusions = packageExclusions;
		this.servicesId = servicesId;
		this.cancellationPolicy = cancellationPolicy;
		this.packageAmenities = packageAmenities;
	}

	public PackageTable(ThemeTable themeTable, SupplierTable supplierTable,
			ItineraryTable itineraryTable,
			ItineraryTypeLookupTable itineraryTypeLookupTable,
			DestinationTable destinationTable,
			PackageBudgetLookupTable packageBudgetLookupTable,
			CurrencyLookupTable currencyLookupTable, CountryTable countryTable,
			PackageTypeLookupTable packageTypeLookupTable,
			HotelTable hotelTable,
			PackageCategoryLookupTable packageCategoryLookupTable,
			MealPlanLookupTable mealPlanLookupTable, String packageId,
			String packageName, int numberOfNights, int numberOfDays,
			String packageDescription, String bestSeason, Date validFrom,
			Date validTo, Date bookingFrom, Date bookingTo,
			String packageHighlights, String termsAndConditions,
			String packageInclusions, String packageExclusions, int servicesId,
			String cancellationPolicy, String packageAmenities,
			Integer packageStatus, Integer originPoints, Set priceTables,
			Set servicesLookupTables) {
		this.themeTable = themeTable;
		this.supplierTable = supplierTable;
		this.itineraryTable = itineraryTable;
		this.itineraryTypeLookupTable = itineraryTypeLookupTable;
		this.destinationTable = destinationTable;
		this.packageBudgetLookupTable = packageBudgetLookupTable;
		this.currencyLookupTable = currencyLookupTable;
		this.countryTable = countryTable;
		this.packageTypeLookupTable = packageTypeLookupTable;
		this.hotelTable = hotelTable;
		this.packageCategoryLookupTable = packageCategoryLookupTable;
		this.mealPlanLookupTable = mealPlanLookupTable;
		this.packageId = packageId;
		this.packageName = packageName;
		this.numberOfNights = numberOfNights;
		this.numberOfDays = numberOfDays;
		this.packageDescription = packageDescription;
		this.bestSeason = bestSeason;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.bookingFrom = bookingFrom;
		this.bookingTo = bookingTo;
		this.packageHighlights = packageHighlights;
		this.termsAndConditions = termsAndConditions;
		this.packageInclusions = packageInclusions;
		this.packageExclusions = packageExclusions;
		this.servicesId = servicesId;
		this.cancellationPolicy = cancellationPolicy;
		this.packageAmenities = packageAmenities;
		this.packageStatus = packageStatus;
		this.originPoints = originPoints;
		this.priceTables = priceTables;
		this.servicesLookupTables = servicesLookupTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "theme")
	public ThemeTable getThemeTable() {
		return this.themeTable;
	}

	public void setThemeTable(ThemeTable themeTable) {
		this.themeTable = themeTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_supplier")
	public SupplierTable getSupplierTable() {
		return this.supplierTable;
	}

	public void setSupplierTable(SupplierTable supplierTable) {
		this.supplierTable = supplierTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itinerary_id")
	public ItineraryTable getItineraryTable() {
		return this.itineraryTable;
	}

	public void setItineraryTable(ItineraryTable itineraryTable) {
		this.itineraryTable = itineraryTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itinerary_type")
	public ItineraryTypeLookupTable getItineraryTypeLookupTable() {
		return this.itineraryTypeLookupTable;
	}

	public void setItineraryTypeLookupTable(
			ItineraryTypeLookupTable itineraryTypeLookupTable) {
		this.itineraryTypeLookupTable = itineraryTypeLookupTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_destinations", nullable = false)
	public DestinationTable getDestinationTable() {
		return this.destinationTable;
	}

	public void setDestinationTable(DestinationTable destinationTable) {
		this.destinationTable = destinationTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_budget")
	public PackageBudgetLookupTable getPackageBudgetLookupTable() {
		return this.packageBudgetLookupTable;
	}

	public void setPackageBudgetLookupTable(
			PackageBudgetLookupTable packageBudgetLookupTable) {
		this.packageBudgetLookupTable = packageBudgetLookupTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_currency")
	public CurrencyLookupTable getCurrencyLookupTable() {
		return this.currencyLookupTable;
	}

	public void setCurrencyLookupTable(CurrencyLookupTable currencyLookupTable) {
		this.currencyLookupTable = currencyLookupTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country", nullable = false)
	public CountryTable getCountryTable() {
		return this.countryTable;
	}

	public void setCountryTable(CountryTable countryTable) {
		this.countryTable = countryTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_type", nullable = false)
	public PackageTypeLookupTable getPackageTypeLookupTable() {
		return this.packageTypeLookupTable;
	}

	public void setPackageTypeLookupTable(
			PackageTypeLookupTable packageTypeLookupTable) {
		this.packageTypeLookupTable = packageTypeLookupTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_hotels")
	public HotelTable getHotelTable() {
		return this.hotelTable;
	}

	public void setHotelTable(HotelTable hotelTable) {
		this.hotelTable = hotelTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_category", nullable = false)
	public PackageCategoryLookupTable getPackageCategoryLookupTable() {
		return this.packageCategoryLookupTable;
	}

	public void setPackageCategoryLookupTable(
			PackageCategoryLookupTable packageCategoryLookupTable) {
		this.packageCategoryLookupTable = packageCategoryLookupTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meal_plan")
	public MealPlanLookupTable getMealPlanLookupTable() {
		return this.mealPlanLookupTable;
	}

	public void setMealPlanLookupTable(MealPlanLookupTable mealPlanLookupTable) {
		this.mealPlanLookupTable = mealPlanLookupTable;
	}

	@Column(name = "package_id", nullable = false, length = 20)
	public String getPackageId() {
		return this.packageId;
	}

	public void setPackageId(String packageId) {
		this.packageId = packageId;
	}

	@Column(name = "package_name", nullable = false, length = 40)
	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	@Column(name = "number_of_nights", nullable = false)
	public int getNumberOfNights() {
		return this.numberOfNights;
	}

	public void setNumberOfNights(int numberOfNights) {
		this.numberOfNights = numberOfNights;
	}

	@Column(name = "number_of_days", nullable = false)
	public int getNumberOfDays() {
		return this.numberOfDays;
	}

	public void setNumberOfDays(int numberOfDays) {
		this.numberOfDays = numberOfDays;
	}

	@Column(name = "package_description", nullable = false, length = 300)
	public String getPackageDescription() {
		return this.packageDescription;
	}

	public void setPackageDescription(String packageDescription) {
		this.packageDescription = packageDescription;
	}

	@Column(name = "best_season", length = 40)
	public String getBestSeason() {
		return this.bestSeason;
	}

	public void setBestSeason(String bestSeason) {
		this.bestSeason = bestSeason;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_from", nullable = false, length = 10)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_to", nullable = false, length = 10)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "booking_from", nullable = false, length = 10)
	public Date getBookingFrom() {
		return this.bookingFrom;
	}

	public void setBookingFrom(Date bookingFrom) {
		this.bookingFrom = bookingFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "booking_to", nullable = false, length = 10)
	public Date getBookingTo() {
		return this.bookingTo;
	}

	public void setBookingTo(Date bookingTo) {
		this.bookingTo = bookingTo;
	}

	@Column(name = "package_highlights", nullable = false, length = 300)
	public String getPackageHighlights() {
		return this.packageHighlights;
	}

	public void setPackageHighlights(String packageHighlights) {
		this.packageHighlights = packageHighlights;
	}

	@Column(name = "terms_and_conditions", nullable = false, length = 1000)
	public String getTermsAndConditions() {
		return this.termsAndConditions;
	}

	public void setTermsAndConditions(String termsAndConditions) {
		this.termsAndConditions = termsAndConditions;
	}

	@Column(name = "package_inclusions", nullable = false, length = 300)
	public String getPackageInclusions() {
		return this.packageInclusions;
	}

	public void setPackageInclusions(String packageInclusions) {
		this.packageInclusions = packageInclusions;
	}

	@Column(name = "package_exclusions", nullable = false, length = 300)
	public String getPackageExclusions() {
		return this.packageExclusions;
	}

	public void setPackageExclusions(String packageExclusions) {
		this.packageExclusions = packageExclusions;
	}

	@Column(name = "services_id", nullable = false)
	public int getServicesId() {
		return this.servicesId;
	}

	public void setServicesId(int servicesId) {
		this.servicesId = servicesId;
	}

	@Column(name = "cancellation_policy", nullable = false, length = 300)
	public String getCancellationPolicy() {
		return this.cancellationPolicy;
	}

	public void setCancellationPolicy(String cancellationPolicy) {
		this.cancellationPolicy = cancellationPolicy;
	}

	@Column(name = "package_amenities", nullable = false, length = 300)
	public String getPackageAmenities() {
		return this.packageAmenities;
	}

	public void setPackageAmenities(String packageAmenities) {
		this.packageAmenities = packageAmenities;
	}

	@Column(name = "package_status")
	public Integer getPackageStatus() {
		return this.packageStatus;
	}

	public void setPackageStatus(Integer packageStatus) {
		this.packageStatus = packageStatus;
	}

	@Column(name = "origin_points")
	public Integer getOriginPoints() {
		return this.originPoints;
	}

	public void setOriginPoints(Integer originPoints) {
		this.originPoints = originPoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packageTable")
	public Set getPriceTables() {
		return this.priceTables;
	}

	public void setPriceTables(Set priceTables) {
		this.priceTables = priceTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packageTable")
	public Set getServicesLookupTables() {
		return this.servicesLookupTables;
	}

	public void setServicesLookupTables(Set servicesLookupTables) {
		this.servicesLookupTables = servicesLookupTables;
	}

}
