package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PriceTable generated by hbm2java
 */
@Entity
@Table(name = "price_table", catalog = "itradb")
public class PriceTable implements java.io.Serializable {

	private Integer id;
	private PackageTable packageTable;
	private Integer defaultCity;
	private String city;
	private Double adultSingleSharing;
	private Double adultTwinSharing;
	private Double adultTripleSharing;
	private Double childWithBed;
	private Double childWithoutBed;
	private Double infant;
	private Double extraBed;

	public PriceTable() {
	}

	public PriceTable(PackageTable packageTable, Integer defaultCity,
			String city, Double adultSingleSharing, Double adultTwinSharing,
			Double adultTripleSharing, Double childWithBed,
			Double childWithoutBed, Double infant, Double extraBed) {
		this.packageTable = packageTable;
		this.defaultCity = defaultCity;
		this.city = city;
		this.adultSingleSharing = adultSingleSharing;
		this.adultTwinSharing = adultTwinSharing;
		this.adultTripleSharing = adultTripleSharing;
		this.childWithBed = childWithBed;
		this.childWithoutBed = childWithoutBed;
		this.infant = infant;
		this.extraBed = extraBed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "package_id")
	public PackageTable getPackageTable() {
		return this.packageTable;
	}

	public void setPackageTable(PackageTable packageTable) {
		this.packageTable = packageTable;
	}

	@Column(name = "default_city")
	public Integer getDefaultCity() {
		return this.defaultCity;
	}

	public void setDefaultCity(Integer defaultCity) {
		this.defaultCity = defaultCity;
	}

	@Column(name = "city", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "adult_single_sharing", precision = 22, scale = 0)
	public Double getAdultSingleSharing() {
		return this.adultSingleSharing;
	}

	public void setAdultSingleSharing(Double adultSingleSharing) {
		this.adultSingleSharing = adultSingleSharing;
	}

	@Column(name = "adult_twin_sharing", precision = 22, scale = 0)
	public Double getAdultTwinSharing() {
		return this.adultTwinSharing;
	}

	public void setAdultTwinSharing(Double adultTwinSharing) {
		this.adultTwinSharing = adultTwinSharing;
	}

	@Column(name = "adult_triple_sharing", precision = 22, scale = 0)
	public Double getAdultTripleSharing() {
		return this.adultTripleSharing;
	}

	public void setAdultTripleSharing(Double adultTripleSharing) {
		this.adultTripleSharing = adultTripleSharing;
	}

	@Column(name = "child_with_bed", precision = 22, scale = 0)
	public Double getChildWithBed() {
		return this.childWithBed;
	}

	public void setChildWithBed(Double childWithBed) {
		this.childWithBed = childWithBed;
	}

	@Column(name = "child_without_bed", precision = 22, scale = 0)
	public Double getChildWithoutBed() {
		return this.childWithoutBed;
	}

	public void setChildWithoutBed(Double childWithoutBed) {
		this.childWithoutBed = childWithoutBed;
	}

	@Column(name = "infant", precision = 22, scale = 0)
	public Double getInfant() {
		return this.infant;
	}

	public void setInfant(Double infant) {
		this.infant = infant;
	}

	@Column(name = "extra_bed", precision = 22, scale = 0)
	public Double getExtraBed() {
		return this.extraBed;
	}

	public void setExtraBed(Double extraBed) {
		this.extraBed = extraBed;
	}

}
