package com.itravel.model;
// default package
// Generated 26 Mar, 2014 6:29:53 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SupplierTable generated by hbm2java
 */
@Entity
@Table(name = "supplier_table", catalog = "itradb")
public class SupplierTable implements java.io.Serializable {

	private Integer id;
	private DestinationTable destinationTable;
	private CountryTable countryTable;
	private String supplierName;
	private String supplierCompany;
	private String supplierDescription;
	private String supplierPanNo;
	private Integer supplierBankAccNo;
	private String supplierBankDetails;
	private String supplierContactPerson;
	private Integer supplierContactPersonNumber;
	private String supplierContactEmail;
	private String supplierCompanyAddress;
	private Integer supplierCompanyContactNumber;
	private String supplierCompanyEmail;
	private Set packageTables = new HashSet(0);

	public SupplierTable() {
	}

	public SupplierTable(DestinationTable destinationTable,
			CountryTable countryTable, String supplierName,
			String supplierCompany, String supplierDescription,
			String supplierPanNo, Integer supplierBankAccNo,
			String supplierBankDetails, String supplierContactPerson,
			Integer supplierContactPersonNumber, String supplierContactEmail,
			String supplierCompanyAddress,
			Integer supplierCompanyContactNumber, String supplierCompanyEmail,
			Set packageTables) {
		this.destinationTable = destinationTable;
		this.countryTable = countryTable;
		this.supplierName = supplierName;
		this.supplierCompany = supplierCompany;
		this.supplierDescription = supplierDescription;
		this.supplierPanNo = supplierPanNo;
		this.supplierBankAccNo = supplierBankAccNo;
		this.supplierBankDetails = supplierBankDetails;
		this.supplierContactPerson = supplierContactPerson;
		this.supplierContactPersonNumber = supplierContactPersonNumber;
		this.supplierContactEmail = supplierContactEmail;
		this.supplierCompanyAddress = supplierCompanyAddress;
		this.supplierCompanyContactNumber = supplierCompanyContactNumber;
		this.supplierCompanyEmail = supplierCompanyEmail;
		this.packageTables = packageTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_company_city")
	public DestinationTable getDestinationTable() {
		return this.destinationTable;
	}

	public void setDestinationTable(DestinationTable destinationTable) {
		this.destinationTable = destinationTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_company_country")
	public CountryTable getCountryTable() {
		return this.countryTable;
	}

	public void setCountryTable(CountryTable countryTable) {
		this.countryTable = countryTable;
	}

	@Column(name = "supplier_name", length = 40)
	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	@Column(name = "supplier_company", length = 40)
	public String getSupplierCompany() {
		return this.supplierCompany;
	}

	public void setSupplierCompany(String supplierCompany) {
		this.supplierCompany = supplierCompany;
	}

	@Column(name = "supplier_description", length = 300)
	public String getSupplierDescription() {
		return this.supplierDescription;
	}

	public void setSupplierDescription(String supplierDescription) {
		this.supplierDescription = supplierDescription;
	}

	@Column(name = "supplier_pan_no", length = 10)
	public String getSupplierPanNo() {
		return this.supplierPanNo;
	}

	public void setSupplierPanNo(String supplierPanNo) {
		this.supplierPanNo = supplierPanNo;
	}

	@Column(name = "supplier_bank_acc_no")
	public Integer getSupplierBankAccNo() {
		return this.supplierBankAccNo;
	}

	public void setSupplierBankAccNo(Integer supplierBankAccNo) {
		this.supplierBankAccNo = supplierBankAccNo;
	}

	@Column(name = "supplier_bank_details", length = 200)
	public String getSupplierBankDetails() {
		return this.supplierBankDetails;
	}

	public void setSupplierBankDetails(String supplierBankDetails) {
		this.supplierBankDetails = supplierBankDetails;
	}

	@Column(name = "supplier_contact_person", length = 40)
	public String getSupplierContactPerson() {
		return this.supplierContactPerson;
	}

	public void setSupplierContactPerson(String supplierContactPerson) {
		this.supplierContactPerson = supplierContactPerson;
	}

	@Column(name = "supplier_contact_person_number")
	public Integer getSupplierContactPersonNumber() {
		return this.supplierContactPersonNumber;
	}

	public void setSupplierContactPersonNumber(
			Integer supplierContactPersonNumber) {
		this.supplierContactPersonNumber = supplierContactPersonNumber;
	}

	@Column(name = "supplier_contact_email", length = 40)
	public String getSupplierContactEmail() {
		return this.supplierContactEmail;
	}

	public void setSupplierContactEmail(String supplierContactEmail) {
		this.supplierContactEmail = supplierContactEmail;
	}

	@Column(name = "supplier_company_address", length = 300)
	public String getSupplierCompanyAddress() {
		return this.supplierCompanyAddress;
	}

	public void setSupplierCompanyAddress(String supplierCompanyAddress) {
		this.supplierCompanyAddress = supplierCompanyAddress;
	}

	@Column(name = "supplier_company_contact_number")
	public Integer getSupplierCompanyContactNumber() {
		return this.supplierCompanyContactNumber;
	}

	public void setSupplierCompanyContactNumber(
			Integer supplierCompanyContactNumber) {
		this.supplierCompanyContactNumber = supplierCompanyContactNumber;
	}

	@Column(name = "supplier_company_email", length = 40)
	public String getSupplierCompanyEmail() {
		return this.supplierCompanyEmail;
	}

	public void setSupplierCompanyEmail(String supplierCompanyEmail) {
		this.supplierCompanyEmail = supplierCompanyEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierTable")
	public Set getPackageTables() {
		return this.packageTables;
	}

	public void setPackageTables(Set packageTables) {
		this.packageTables = packageTables;
	}

}
